minimum_pre_commit_version: 3.0.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: detect-private-key
    -   id: debug-statements
- repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
  rev: v0.6.9
  hooks:
    - id: cmake-format
